### ISSUE TITLE
Photographer

### ISSUE THREAD

**Issue by seano-vs** [seano-vs/KaySeanWeddingPlanning#8]

**Comment by seano-vs** [comment]
It seems that, out of the photographers that have the credentials we are looking for, this is the range we are looking at:

8 hrs: ~$3600

6 hrs: ~$2500

4 hrs: ~$1800

I've hit up a few more people asking about price sheets, but we'll see what happens

**Comment by seano-vs** [comment]
Just needed to update that I called Anaya and they were super chill, looking forward to hearing back from them

**Comment by seano-vs** [comment]
OK, change of plans. Need to re-run all this with a video option

**Comment by seano-vs** [comment]
Folks I have reached out to: 

- Anaya Photography Studio
- Swan Photography
- Casey Addason (wants to have a call to discuss)
- Vanessa @ vfineemoments

**Comment by seano-vs** [comment]
Swan Photo is not available, damn I liked them. They suggested Carissa + Ben Photography but they don't fit our stipulations :(

**Comment by seano-vs** [comment]
Heard from Casey. We're going to chat soon, but I'm concerned about the fact that there are no prices listed anywhere on the site.

**Comment by ksdesportes** [comment]
Additional Contacts: 

- Alicia Lucia -- https://www.alicialucia.com/ 
    - Contacted with pricing [here for photography](https://www.alicialucia.com/2024pricing) (password: ALP2024) and [here for videography](http://www.alicialucia.com/videocollection) 
    - Summary: photography packages $6000/8hrs $5000/6hrs & $4000/4hrs || videography packages  $3400/8hrs & $2400/6hrs. 
- The Livelys -- https://www.the-livelys.com/contact
    - Contacted through their website

**Comment by seano-vs** [comment]
Photographer is done! We booked Casey Addason and paid up front

https://www.addasonphoto.com/

**Comment by ksdesportes** [comment]
Scheduling engagement photoshoot July 5th Friday 1 or 2pm (or back up on Wednesday July 3rd). Asked about including family in some of the photos.
